sonar.projectKey=thesapan_url-shortener-ztm
sonar.organization=sapan-shah


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=url-shortener-ztm
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
